workspace:
  base: /var/www/owncloud
  path: apps/password_policy



branches: [master release*, release/*]

pipeline:
  install-server:
    image: owncloudci/core
    version: ${OC_VERSION}
    pull: true
    db_type: ${DB_TYPE}
    db_name: ${DB_NAME}
    db_host: ${DB_TYPE}
    db_username: autotest
    db_password: owncloud
    exclude: apps/password_policy

  install-app:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - cd /var/www/owncloud/
      - php occ a:l
      - php occ a:e testing
      - php occ a:l
      - php occ config:system:set trusted_domains 1 --value=owncloud
      - php occ log:manage --level 0

  owncloud-log:
    image: owncloud/ubuntu:16.04
    detach: true
    pull: true
    commands:
      - tail -f /var/www/owncloud/data/owncloud.log

  code-compliance-check:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - cd /var/www/owncloud/apps/password_policy
      - make test-php-style

  fix-permissions:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - cd /var/www/owncloud/
      - chown www-data * -R

  phpunit-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - PHP_VERSION=${PHP_VERSION}
    commands:
      - cd /var/www/owncloud/apps/password_policy
      - make test-php-unit
    when:
      matrix:
        TEST_SUITE: phpunit

  scrutinizer:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - wget -q https://scrutinizer-ci.com/ocular.phar
      - php ocular.phar code-coverage:upload --format=php-clover tests/Unit/clover.xml
    when:
      matrix:
        TEST_SUITE: phpunit

  codecov:
    image: plugins/codecov:2
    secrets: [codecov_token]
    pull: true
    flags:
      - ${TEST_SUITE}
    files:
      - tests/unit/clover.xml
    when:
      event: [push, pull_request]
      matrix:
        TEST_SUITE: phpunit
        PHP_VERSION: 7.1
        DB_TYPE: mysql

  notify:
    image: plugins/slack:1
    pull: true
    secrets: [ slack_webhook ]
    channel: builds
    when:
      status: [ failure, changed ]
      event: [ push, tag ]

services:
  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_USER=autotest
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=owncloud
    when:
      matrix:
        DB_TYPE: mysql

  pgsql:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=autotest
      - POSTGRES_PASSWORD=owncloud
      - POSTGRES_DB=${DB_NAME}
    when:
      matrix:
        DB_TYPE: pgsql

  oci:
    image: deepdiver/docker-oracle-xe-11g
    environment:
       - ORACLE_USER=system
       - ORACLE_PASSWORD=oracle
       - ORACLE_DB=${DB_NAME}
    when:
      matrix:
        DB_TYPE: oci

matrix:
  include:
    # Unit Tests
    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: mysql
      DB_NAME: owncloud

    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: pgsql
      DB_NAME: owncloud

    - PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: oci
      DB_NAME: XE

    - PHP_VERSION: 7.2
      OC_VERSION: daily-master-qa
      TEST_SUITE: phpunit
      DB_TYPE: mysql
      DB_NAME: owncloud

    - PHP_VERSION: 5.6
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: phpunit
      DB_TYPE: mysql
      DB_NAME: owncloud

    - PHP_VERSION: 7.0
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: phpunit
      DB_TYPE: mysql
      DB_NAME: owncloud

    - PHP_VERSION: 7.0
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: phpunit
      DB_TYPE: pgsql
      DB_NAME: owncloud

    - PHP_VERSION: 7.0
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: phpunit
      DB_TYPE: oci
      DB_NAME: XE

    - PHP_VERSION: 7.1
      OC_VERSION: daily-stable10-qa
      TEST_SUITE: phpunit
      DB_TYPE: mysql
      DB_NAME: owncloud
